package com.myspace.drools_training_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FamilyVisaApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int applicationId;
	private java.util.List<java.lang.String> passportNumbers;
	private java.time.LocalDate visitStartDate;
	private java.time.LocalDate visitEndDate;

	public FamilyVisaApplication() {
	}

	public int getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(int applicationId) {
		this.applicationId = applicationId;
	}

	public java.util.List<java.lang.String> getPassportNumbers() {
		return this.passportNumbers;
	}

	public void setPassportNumbers(
			java.util.List<java.lang.String> passportNumbers) {
		this.passportNumbers = passportNumbers;
	}

	public java.time.LocalDate getVisitStartDate() {
		return this.visitStartDate;
	}

	public void setVisitStartDate(java.time.LocalDate visitStartDate) {
		this.visitStartDate = visitStartDate;
	}

	public java.time.LocalDate getVisitEndDate() {
		return this.visitEndDate;
	}

	public void setVisitEndDate(java.time.LocalDate visitEndDate) {
		this.visitEndDate = visitEndDate;
	}

	public FamilyVisaApplication(int applicationId,
			java.util.List<java.lang.String> passportNumbers,
			java.time.LocalDate visitStartDate, java.time.LocalDate visitEndDate) {
		this.applicationId = applicationId;
		this.passportNumbers = passportNumbers;
		this.visitStartDate = visitStartDate;
		this.visitEndDate = visitEndDate;
	}
	
    @Override
    public String toString() {
        return String.format("FamilyVisaApplication[#%d, %s]", applicationId, join(passportNumbers));
    }

    public static FamilyVisaApplicationBuilder newBuilder() {
       return new FamilyVisaApplicationBuilder();
    }


    public static final class FamilyVisaApplicationBuilder {
       private int applicationId;
       private java.util.List<java.lang.String> passportNumbers = new ArrayList<>();
       private java.time.LocalDate visitStartDate;
       private java.time.LocalDate visitEndDate;
       
       
       private FamilyVisaApplicationBuilder() {
       }


       public FamilyVisaApplicationBuilder withApplicationId(int applicationId) {
          this.applicationId = applicationId;
          return this;
       }

       public FamilyVisaApplicationBuilder withPassportNumbers(java.util.List<java.lang.String> passportNumbers) {
          this.passportNumbers = passportNumbers;
          return this;
       }

       public FamilyVisaApplicationBuilder withVisitStartDate(java.time.LocalDate visitStartDate) {
          this.visitStartDate = visitStartDate;
          return this;
       }

       public FamilyVisaApplicationBuilder withVisitEndDate(java.time.LocalDate visitEndDate) {
          this.visitEndDate = visitEndDate;
          return this;
       }

       public FamilyVisaApplication build() {
          FamilyVisaApplication familyVisaApplication = new FamilyVisaApplication(applicationId);
          familyVisaApplication.visitEndDate = this.visitEndDate;
          familyVisaApplication.passportNumbers = this.passportNumbers;
          familyVisaApplication.visitStartDate = this.visitStartDate;
          return familyVisaApplication;
       }
    }
}