package com.myspace.drools_training_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvalidVisaApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.drools_training_master.VisaApplication visaApplication;

	public InvalidVisaApplication() {
	}

	public com.myspace.drools_training_master.VisaApplication getVisaApplication() {
		return this.visaApplication;
	}

	public void setVisaApplication(
			com.myspace.drools_training_master.VisaApplication visaApplication) {
		this.visaApplication = visaApplication;
	}

	public InvalidVisaApplication(
			com.myspace.drools_training_master.VisaApplication visaApplication) {
		this.visaApplication = visaApplication;
	}

}