package com.myspace.drools_training_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvalidVisaApplication implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public InvalidVisaApplication() {
    }




}