package com.myspace.drools_training_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvalidFamilyVisaApplication implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.drools_training_master.FamilyVisaApplication familyVisaApplication;

	public InvalidFamilyVisaApplication() {
	}

	public com.myspace.drools_training_master.FamilyVisaApplication getFamilyVisaApplication() {
		return this.familyVisaApplication;
	}

	public void setFamilyVisaApplication(
			com.myspace.drools_training_master.FamilyVisaApplication familyVisaApplication) {
		this.familyVisaApplication = familyVisaApplication;
	}

	public InvalidFamilyVisaApplication(
			com.myspace.drools_training_master.FamilyVisaApplication familyVisaApplication) {
		this.familyVisaApplication = familyVisaApplication;
	}

}